import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

export default function Home() {
  const [topups, setTopups] = useState([]);

  const getData = () => {
    fetch("http://192.168.2.123:3000/api/hello")
      .then((res) => res.json())
      .then((data) => setTopups(data));
  };

  useEffect(() => {
    getData();
  }, []);

  console.log(topups);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {topups.map((topup, index) => (
        <p key={index}>{topup.name}</p>
      ))}
    </div>
  );
}
