import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import { useTopups } from "../contexts/TopupContext";
import Topups from "../components/Topups";

export default function Home() {
  const topups = useTopups();

  return (
    <div>
      <Head>
        <title>SPNV Topups</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spnv.png" />
      </Head>
      <Topups />
      {/* {topups.map((topup, index) => (
        <p key={index}>{topup.name}</p>
      ))} */}
    </div>
  );
}
